# Generated by Django 5.2.16 on 2026-08-05 18:42

import apps.accounts.managers
import apps.accounts.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('user_type', models.CharField(choices=[('customer', 'Cliente'), ('worker', 'Trabajador')], default='customer', max_length=20, verbose_name='Tipo de usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso al admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', apps.accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, validators=[apps.accounts.validators.validate_rut], verbose_name='RUT')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Direccion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de cliente',
                'verbose_name_plural': 'Perfiles de clientes',
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[apps.accounts.validators.validate_rut], verbose_name='RUT')),
                ('role', models.CharField(choices=[('jefatura', 'Jefatura'), ('administracion', 'Administracion'), ('rrhh', 'Recursos Humanos'), ('venta', 'Venta')], max_length=20, verbose_name='Rol')),
                ('afp', models.CharField(blank=True, max_length=100, verbose_name='AFP')),
                ('health_system', models.CharField(choices=[('fonasa', 'Fonasa'), ('isapre', 'Isapre')], default='fonasa', max_length=10, verbose_name='Sistema de salud')),
                ('contract_type', models.CharField(choices=[('indefinido', 'Indefinido'), ('plazo_fijo', 'Plazo fijo'), ('por_obra', 'Por obra o faena')], default='indefinido', max_length=20, verbose_name='Tipo de contrato')),
                ('base_salary', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Sueldo base (CLP)')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de contratacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de trabajador',
                'verbose_name_plural': 'Perfiles de trabajadores',
            },
        ),
    ]
