# Generated by Django 5.2.16 on 2026-08-08 00:09

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='base_salary',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[apps.accounts.validators.validate_minimum_wage], verbose_name='Sueldo base (CLP)'),
        ),
    ]
