# Generated by Django 5.2.16 on 2026-08-06 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numero de pedido')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Nombre de contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Correo de contacto')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Telefono de contacto')),
                ('contact_rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('listo_retiro', 'Listo para retiro'), ('entregado', 'Entregado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('net_total', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total neto')),
                ('iva_total', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total IVA')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente registrado')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Nombre del producto')),
                ('product_sku', models.CharField(max_length=30, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price_net', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio neto unitario')),
                ('unit_price_iva', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='IVA unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Linea de pedido',
                'verbose_name_plural': 'Lineas de pedido',
            },
        ),
    ]
