# Generated by Django 5.2.16 on 2026-08-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Madera & Vida', max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('address', models.CharField(max_length=255, verbose_name='Direccion')),
                ('schedule', models.CharField(help_text='Ej: Lunes a Viernes 9:00 - 18:00, Sabado 9:00 - 13:00', max_length=255, verbose_name='Horario de atencion')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
            ],
            options={
                'verbose_name': 'Informacion de la empresa',
                'verbose_name_plural': 'Informacion de la empresa',
            },
        ),
    ]
