# Generated by Django 5.2.16 on 2026-08-07 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('product_update', 'Producto modificado'), ('product_create', 'Producto creado'), ('product_deactivate', 'Producto desactivado'), ('product_activate', 'Producto activado'), ('product_delete', 'Producto eliminado'), ('order_status_change', 'Estado de pedido modificado'), ('worker_password_reset', 'Contraseña de trabajador reseteada')], max_length=30, verbose_name='Accion')),
                ('entity', models.CharField(help_text='Ej: Product, Order, CustomUser', max_length=100, verbose_name='Entidad')),
                ('entity_id', models.CharField(blank=True, max_length=50, verbose_name='ID de la entidad')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='Antes')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='Despues')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Direccion IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizo la accion')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
