# Generated by Django 5.2.16 on 2026-08-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Se muestra junto a la descripción en la página principal.', null=True, upload_to='company/', verbose_name='Foto principal'),
        ),
    ]
