# Generated by Django 5.2.16 on 2026-08-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyinfo_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre AFP')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Incluye el 10% obligatorio más la comisión de la AFP.', max_digits=5, verbose_name='Porcentaje total (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Configuración AFP',
                'verbose_name_plural': 'Configuraciones AFP',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MinimumWageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Sueldo mínimo (CLP)')),
                ('effective_date', models.DateField(verbose_name='Vigente desde')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Configuración de sueldo mínimo',
                'verbose_name_plural': 'Configuraciones de sueldo mínimo',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('product_update', 'Producto modificado'), ('product_create', 'Producto creado'), ('product_deactivate', 'Producto desactivado'), ('product_activate', 'Producto activado'), ('product_delete', 'Producto eliminado'), ('order_status_change', 'Estado de pedido modificado'), ('worker_password_reset', 'Contraseña de trabajador reseteada'), ('worker_create', 'Trabajador creado'), ('payroll_generated', 'Liquidación de sueldo generada')], max_length=30, verbose_name='Accion'),
        ),
    ]
