# Generated by Django 5.2.16 on 2026-08-08 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_workerprofile_base_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Horas extras')),
                ('hourly_rate', models.DecimalField(decimal_places=0, editable=False, max_digits=10, verbose_name='Valor hora ordinaria')),
                ('overtime_rate', models.DecimalField(decimal_places=0, editable=False, max_digits=10, verbose_name='Valor hora extra (1.5x)')),
                ('total', models.DecimalField(decimal_places=0, editable=False, max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='accounts.workerprofile', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Registro de horas extras',
                'verbose_name_plural': 'Registros de horas extras',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('anticipo', 'Anticipo'), ('bono', 'Bono'), ('descuento', 'Descuento')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto (CLP)')),
                ('period', models.DateField(help_text='Cualquier día del mes correspondiente; se normaliza al día 1.', verbose_name='Periodo (mes)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='accounts.workerprofile', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Anticipo / bono / descuento',
                'verbose_name_plural': 'Anticipos, bonos y descuentos',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Se normaliza al día 1 del mes.', verbose_name='Periodo (mes)')),
                ('base_salary', models.DecimalField(decimal_places=0, editable=False, max_digits=10, verbose_name='Sueldo base')),
                ('overtime_total', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10, verbose_name='Total horas extras')),
                ('bonuses_total', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10, verbose_name='Total bonos')),
                ('taxable_income', models.DecimalField(decimal_places=0, editable=False, max_digits=10, verbose_name='Imponible')),
                ('afp_name', models.CharField(editable=False, max_length=50, verbose_name='AFP aplicada')),
                ('afp_percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='% AFP aplicado')),
                ('afp_amount', models.DecimalField(decimal_places=0, editable=False, max_digits=10, verbose_name='Cotización AFP')),
                ('health_amount', models.DecimalField(decimal_places=0, editable=False, max_digits=10, verbose_name='Cotización salud (7%)')),
                ('advances_total', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10, verbose_name='Total anticipos')),
                ('deductions_total', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10, verbose_name='Total descuentos')),
                ('net_pay', models.DecimalField(decimal_places=0, editable=False, max_digits=10, verbose_name='Líquido a pagar')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('pagada', 'Pagada')], default='emitida', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Generada')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='accounts.workerprofile', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Liquidación de sueldo',
                'verbose_name_plural': 'Liquidaciones de sueldo',
                'ordering': ['-period'],
                'unique_together': {('worker', 'period')},
            },
        ),
    ]
