# Generated by Django 5.2.16 on 2026-08-05 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='SKU')),
                ('price_net', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio neto (CLP)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='Umbral de alerta de stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo (visible en tienda)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
    ]
