# Generated by Django 5.2.16 on 2026-08-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='next_sku_seq',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='sku_prefix',
            field=models.CharField(blank=True, help_text='Se genera automáticamente si se deja en blanco (ej. "Muebles" → "MUE").', max_length=8, null=True, unique=True, verbose_name='Prefijo SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='SKU'),
        ),
    ]
